### ISSUE TITLE
Error invoking action "click->nested-rondo#removeField"

### ISSUE THREAD

**Issue by martijnenco** [hungle00/rondo_form#1]
![image](https://github.com/hungle00/rondo_form/assets/9299454/85e24c45-bbcd-4004-9025-2b71c3b33d15)
Looks like it is required to have the `class="nested-fields"`
Would have been nice if would just figure out the closest _destroy by itself, or set a target in de html. Instead of querieng on random classes :)

**Comment by hungle00** [comment]
@martijnenco Thanks for the first issue of this repo. I fixed this problem in this PR #3.
Now you can pass the class name that wrapped each field to the `data-nested-rondo-field-class-value`. If not, it will query the closest parent element and remove it.

``` html
<div data-controller="nested-rondo" data-nested-rondo-field-class-value="custom-field">
```
In your partial:
```html
<div class="custom-field">...</div>
```
