### ISSUE TITLE
Destroy doesn't work on update?

### ISSUE THREAD

**Issue by czepesch** [hungle00/rondo_form#12]
Hi! 
Using gem for quite some time, but now the first time I tried to edit and update existing **invoice** model which has **line_items** associated with it, it has few and try to remove one of them.
When I hit Update invoice it doesn't work, the line item is still there.

In the server logs there is nothing about destroy with value "1"

DOM has one element for each line item:

`<input autocomplete="off" type="hidden" value="false" name="invoice[line_items_attributes][0][_destroy]" id="invoice_line_items_attributes_0__destroy">`

`<input autocomplete="off" type="hidden" value="false" name="invoice[line_items_attributes][1][_destroy]" id="invoice_line_items_attributes_1__destroy">`

but when I click remove item I can't see in the DOM hidden field for destroy with value "1" also.

invoice params has:
`line_items_attributes: [:name, :unit, :tax_rate, :cost, :quantity, :amount, :_destroy, :id])`

and invoice model has:
  `accepts_nested_attributes_for :line_items, reject_if: :all_blank, allow_destroy: true`

Can you confirm that it actually working correctly?
Any hints for debugging this?

Thanks!

**Comment by hungle00** [comment]
@czepesch It works correctly with my app and some other devs.
What version of the gem do you use?
Or did you follow this instruction:

> `data-nested-rondo-field-class-value` is used to detect the element that needs to be removed. Its value must match an element's class name that wraps the partial. If you do not declare it, it will default remove the closest parent element.

**Comment by czepesch** [comment]
@hungle00 
I'm sorry, it was an issue on my side. It's indeed working well.

I have another stimulus controller for calculating and displaying the amount of the invoice depending on adding or removing line items which was conflicting with rondo_form controller, fixed that.

Thank you
