### ISSUE TITLE
new_{association}_attribute

### ISSUE THREAD

**Issue by royalgiant** [hungle00/rondo_form#2]
Every new form that is added renders with new_{association}.

`
#<ActionController::Parameters {"authenticity_token"=>"3kUjG2E7cVsYIYFgIdTKIgvwe0tgEUuB5WL510s5q515S4-hZnsjv7O-cKv-Q6qAv6b49HPTlxBfl6CpLxQamA", "automation"=>{"name"=>"Pinny 3", "imagination_id"=>"1", "frequencies_attributes"=>{"0"=>{"post_frequency"=>"daily", "days_of_the_week"=>"tuesday", "time_of_day"=>"1:30", "_destroy"=>"false"}, "new_frequencies"=>{"post_frequency"=>"daily", "days_of_the_week"=>"friday", "time_of_day"=>"8:00", "_destroy"=>"false"}}}, "button"=>"", "controller"=>"automations", "action"=>"create"} permitted: false>
`

In this code, if I had added 2 more new frequencies the last one would overwrite the ones before. 

How are you getting around that?

Help is appreciated.

**Comment by hungle00** [comment]
Sorry for the slow feedback!
I fixed this bug. Upgrade to the new version ( 0.2.5 ) and your problem will disappear.
